window.DIM_LIGHT_PROJECTS = {
  order: [
    "ganzi",
    "in-transit",
    "beijing",
    "lost-angel",
    "android",
    "small-town",
    "xiuhu",
    "chengdu-notes",
  ],
  items: {
    ganzi: {
      number: "01",
      type: "work",
      title: "西行甘孜",
      english: "Westward to Ganzi",
      year: "2025",
      place: "Ganzi, Sichuan",
      count: 20,
      cover: 1,
      description:
        "从雾中的山路进入高原。经幡、雪线、陌生的人和辽阔的风景，组成一段不断改变距离的西行。",
    },
    "in-transit": {
      number: "02",
      type: "work",
      title: "往返途中",
      english: "In Transit",
      year: "2025",
      place: "Beijing — Chongqing",
      count: 13,
      cover: 9,
      description:
        "车窗把广阔的土地压缩成一幅幅短暂出现的画面。城市尚未抵达，旅途本身已经成为目的地。",
    },
    beijing: {
      number: "03",
      type: "work",
      title: "京城见闻",
      english: "Notes from Beijing",
      year: "2025",
      place: "Beijing, China",
      count: 14,
      cover: 4,
      description:
        "柳枝、胡同、旧招牌、单车与街口。没有宏大的北京，只有被个人视线留下的普通生活。",
    },
    "lost-angel": {
      number: "04",
      type: "work",
      title: "失落天使",
      english: "Lost Angel",
      year: "2025",
      place: "Chongqing, China",
      count: 10,
      cover: 4,
      description:
        "在县城天台完成的一次共同幻想。翅膀、逆光与水泥边界，让青春短暂悬浮在现实之上。",
    },
    android: {
      number: "05",
      type: "work",
      title: "仿生之前",
      english: "Before the Android",
      year: "2026",
      place: "China",
      count: 8,
      cover: 3,
      description:
        "在机器学会行动以前，人类已经先替它塑造身体、表情与欲望。它们没有智能，却承接着陪伴的想象。",
    },
    "small-town": {
      number: "06",
      type: "work",
      title: "小城故事",
      english: "Small Town Stories",
      year: "Ongoing",
      place: "Bishan, Chongqing",
      count: 18,
      cover: 1,
      description:
        "在不以奇观著称的小城，人物、手艺和日常空间仍在缓慢生长。普通不是限制，而是观看开始的地方。",
    },
    xiuhu: {
      number: "07",
      type: "note",
      title: "秀湖微观",
      english: "Xiuhu, Up Close",
      year: "2025",
      place: "Bishan, Chongqing",
      count: 8,
      cover: 5,
      description:
        "靠近叶片、水滴、蜗牛与睡莲。微小并不等于沉默，生命始终在光线里留下痕迹。",
    },
    "chengdu-notes": {
      number: "08",
      type: "note",
      title: "成都小记",
      english: "Chengdu Notes",
      year: "2025",
      place: "Chengdu, Sichuan",
      count: 10,
      cover: 1,
      description:
        "麦田、房间、花和散落的书。一次短暂停留，没有结论，只留下生活经过之后的温度。",
    },
  },
};
